# 1. URL con puerto y base de datos (Puerto 6543 para Transaction Mode o 5432 para Session Mode)
# Asegúrate de incluir el ':6543/postgres' al final
spring.datasource.url=jdbc:postgresql://aws-1-eu-west-1.pooler.supabase.com:6543/postgres

# 2. Credenciales
# IMPORTANTE: El pooler de Supabase suele requerir el formato 'postgres.[ID_PROYECTO]'
# Si solo pones 'postgres', la conexión podría ser rechazada.
spring.datasource.username=postgres.qjocckjhhiekwsxicneq
spring.datasource.password=BgFpN#dq7w-6GcS

# 3. Driver y Dialecto
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# 4. Otros ajustes
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8080
